# Generated by Django 3.0.6 on 2020-06-08 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SJTUTTA_manage', '0003_auto_20200529_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('commodity_info_type', models.CharField(default='UNK', max_length=5, verbose_name='Type')),
                ('commodity_info_title', models.CharField(default='Commodity 商品', editable=False, max_length=12, verbose_name='Title')),
                ('commodity_info_size', models.CharField(default='One 1 一', editable=False, max_length=12, verbose_name='Size')),
                ('commodity_info_description', models.TextField(blank=True, default='欢迎各位参加.\nWelcome.', verbose_name='Description')),
                ('commodity_info_image', models.TextField(blank=True, default='http://vi.sjtu.edu.cn/uploads/files/caf2f5045c47308250fab3812dfe2003-6896b91594f238b24e67696224948251.png ', verbose_name='Image URL')),
                ('commodity_info_price', models.FloatField(default=2.33, editable=False, verbose_name='Price')),
                ('commodity_status_stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('commodity_status_availability', models.BooleanField(default=True, verbose_name='Availability')),
            ],
            options={
                'verbose_name_plural': 'Store - Items',
            },
        ),
    ]
