# Generated by Django 3.0.6 on 2020-06-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SJTUTTA_manage', '0004_storeitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitems',
            name='commodity_info_description',
            field=models.TextField(blank=True, default='Unfilled', verbose_name='Description'),
        ),
    ]
