# Generated by Django 3.0.6 on 2020-06-10 06:28

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SJTUTTA_manage', '0005_auto_20200608_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('commodity_id', models.CharField(editable=False, max_length=32, verbose_name='Commodity ID')),
                ('item_count', models.PositiveSmallIntegerField(editable=False, verbose_name='Count of Item')),
                ('total_price', models.FloatField(editable=False, verbose_name='Total Price')),
                ('order_datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Order Datetime')),
                ('buyer_email', models.EmailField(editable=False, max_length=254, verbose_name='Customer Email Address')),
                ('seller_info', models.CharField(default='SJTUTTA', editable=False, max_length=255, verbose_name='Seller Info')),
                ('pay_qr_code', models.TextField(default='http://vi.sjtu.edu.cn/uploads/files/caf2f5045c47308250fab3812dfe2003-6896b91594f238b24e67696224948251.png ', editable=False, verbose_name='QR Code URL for Payment')),
                ('order_status', models.CharField(default='order_accepted', max_length=255, verbose_name='Current Order Status')),
            ],
            options={
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.AddField(
            model_name='storeitems',
            name='commodity_info_sold_by',
            field=models.CharField(default='微电子工业', editable=False, max_length=15, verbose_name='Sold By'),
        ),
    ]
